### ISSUE TITLE
issue with android-9.0

### ISSUE THREAD

**Issue by ghost** [zawzaww/aosp-android#1]
18:24:36 Failed to run dumpvars: fork/exec prebuilts/build-tools/linux-x86/bin/ckati: no such file or directory

**Comment by thezawzaw** [comment]
Thank you @bengris32 for your opened issue.
Sorry, I removed this build-tools project path from manifest.
Fixed: https://github.com/zawzaww/pure-aospandroid/commit/223a80755dee6e952a4eae54d932be8c49429dec
Repo sync..

**Comment by ghost** [comment]
alright thanks!
